name: wellness_hub
description: A wellness services application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.1.0
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/spa.jpg
    - assets/images/mental_wellness.jpg
    - assets/images/pet_therapy.jpg
    - assets/images/home_help.jpg
    - assets/images/medicines.jpg
    - assets/images/diet.jpg
    - assets/images/deals_banner.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/profile.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware. 